export const BOTTOM = 'BOTTOM'
export const ONBOARDING_SCREEN = 'ONBOARDING_SCREEN'
export const LOGIN_SCREEN = 'LOGIN_SCREEN'
export const LOGIN_MAIN = 'LOGIN_MAIN'
export const REGISTER_SCREEN = 'REGISTER_SCREEN'
//password reset
export const FORGOT_SCREEN = 'FORGOT_SCREEN'
export const VERIFY_SCREEN = 'VERIFY_SCREEN'
export const NEW_PASSWORD_SCREEN = 'NEW_PASSWORD_SCREEN'

//tab bottom navigator**
//home stack*
export const HOME_SCREEN = 'HOME_SCREEN'
export const DETAIL_SCREEN = 'DETAIL_SCREEN'
export const SEARCH_SCREEN = 'SEARCH_SCREEN'
export const BASIC_SEARCH_SCREEN = 'BASIC_SEARCH_SCREEN'
export const DETAIL_SEARCH_SCREEN = 'DETAIL_SEARCH_SCREEN'

export const SEARCH_RESULT_SCREEN = 'SEARCH_RESULT_SCREEN'
export const CREATE_CONTRACT_FORM_SCREEN = 'CREATE_CONTRACT_FORM_SCREEN'
export const CREATE_ELDER_FORM_SCREEN = 'CREATE_ELDER_FORM_SCREEN'
//Elder 


export const CARERDETAIL_SCREEN = "CARERDETAIL_SCREEN"
export const ELDER_DETAIL_SCREEN = "ELDER_DETAIL_SCREEN"

//price stack*
export const PRICE_SCREEN = 'PRICE_SCREEN'
//order stack*
export const ORDER_SCREEN = 'ORDER_SCREEN'
export const ORDER_DETAIL_SCREEN = 'ORDER_DETAIL_SCREEN'
export const SELECT_LOCATION_SCREEN = 'SELECT_LOCATION_SCREEN'
export const PICKUP_SCREEN = 'PICKUP_SCREEN'
export const PICKUP_SCREEN_INFO = 'PICKUP_SCREEN_INFO'
export const PICKUP_SCREEN_DETAIL = 'PICKUP_SCREEN_DETAIL'
export const PICKUP_SCREEN_DETAIL_QUANTITY = 'PICKUP_SCREEN_DETAIL_QUANTITY'
export const MOMO_PAYMENT_SCREEN = 'MOMO_PAYMENT_SCREEN'
//contract
export const CONTRACT_DETAIL_SERVICE_SCREEN = 'CONTRACT_DETAIL_SERVICE_SCREEN'
export const VIEW_CONTRACT_SCREEN = 'VIEW_CONTRACT_SCREEN'



//chat stack*
export const CHATBOX_SCREEN = 'CHATBOX_SCREEN'
//notification stack*
export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN'
//user profile stack*
export const USER_PROFILE_SCREEN = 'USER_PROFILE_SCREEN'
export const PROFILE_DETAILS_SCREEN = 'PROFILE_DETAILS_SCREEN'
export const EDIT_PROFILE_SCREEN = 'EDIT_PROFILE_SCREEN'
export const CHANGE_PASSWORD_SCREEN = 'CHANGE_PASSWORD_SCREEN'
export const SUPPORT_SCREEN = 'SUPPORT_SCREEN'
export const ABOUT_US_SCREEN = 'ABOUT_US_SCREEN'
export const TERM_SCREEN = 'TERM_SCREEN'
export const CARER_PAID_SCREEN_DETAIL = 'CARER_PAID_SCREEN_DETAIL'
//contract
export const CONTRACT_NON_TRACKING_SERVICE = 'CONTRACT_NON_TRACKING_SERVICE'
export const CONTRACT_TRACKING_SERVICE = 'CONTRACT_TRACKING_SERVICE'
export const CONTRACT_NON_TRACKING_PACKAGE = 'CONTRACT_NON_TRACKING_PACKAGE'
export const CONTRACT_TRACKING_PACKAGE = 'CONTRACT_TRACKING_PACKAGE'

export const CONTRACT_DETAIL_SCREEN = 'CONTRACT_DETAIL_SCREEN'



export const CARER_CONFIRM_CONTRACT_SCREEN = 'CARER_CONFIRM_CONTRACT_SCREEN'
export const CARER_CONFIRM_CONTRACT_DETAIL_SCREEN = 'CARER_CONFIRM_CONTRACT_DETAIL_SCREEN'

//history
export const CARER_BOOKING_HISTORY_SCREEN = 'CARER_BOOKING_HISTORY_SCREEN'
